http {
  server {
      listen 8091;
      root /var/www/html;
      index index.php index.html index.htm;

      location ~ \.php$ {
        include fastcgi_params;
        fastcgi_pass 127.0.0.1:9000; # Must match PHP-FPM listen address
        fastcgi_index index.php;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
    }
  }

}
events {
    worker_connections 1024;
}
